language: node_js
node_js:
  - 12

arch: arm64
os: linux

install:
  - npm install
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: test
      script: npm run coverage
