name: CI

on:
  release:
    types: [created]
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: yarn
      - run: yarn lint
      - run: yarn test
      - run: yarn coverage
      - run: yarn build

  publish-npm:
    if: github.ref == 'refs/heads/master'
    needs:
      - build
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
      - run: |
          yarn install
          yarn build

        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish NPM
        run: |
          yarn release
          git push --follow-tags origin master && npm publish
